LOG-8698: Added support for log management
logentries/lecli pull request #35
Opened 2017-02-01 16:06 UTC by ellynch-r7

2017-02-01 16:15 UTC, ellynch-r7 commented
This PR is basically identical to the previous one for this branch. I've updated the new commands to be the same style as the refactored ones on master -`lecli <action> <resource>`

2017-02-01 17:05 UTC, stopal-r7 commented on tests/examples/misc_examples.py
> +TEST_MANAGEMENT_URL = 'https://rest.logentries.com/management/logs'
this is meant to be https://rest.logentries.com/management i think.

2017-02-01 17:06 UTC, stopal-r7 commented on tests/examples/misc_examples.py
> +MOCK_LOGAPI_URL = 'https://mydummyurl.com/management'
and this should end with /logs

I know that its only for unit tests but for consistency better to fix imho.

2017-02-01 17:08 UTC, stopal-r7 commented on lecli/log/api.py
> +        sys.stdout.write(json.dumps(response.json(), indent=4, sort_keys=True))
can we not use pretty_print_string_as_json util functino here?

2017-02-01 17:08 UTC, ellynch-r7 commented on tests/examples/misc_examples.py
> +MOCK_LOGAPI_URL = 'https://mydummyurl.com/management'
Nah, you're totally right.

Fixed now!

2017-02-01 17:11 UTC, ellynch-r7 commented on lecli/log/api.py
> +        sys.stdout.write(json.dumps(response.json(), indent=4, sort_keys=True))
Yep, will update

2017-02-01 21:07 UTC, stopal-r7 commented on lecli/api_utils.py
> +    print json.dumps(json.loads(text), indent=4, sort_keys=True)
I think we can make this prettier. How you checked tabular library? We are already using it in some other APIs. If it does not work, parsing the response fields is another option. What do you think?

2017-02-01 21:15 UTC, stopal-r7 requested changes
Looks good with a possible prettifying of log objects in the response.

2017-02-02 09:38 UTC, ellynch-r7 commented on lecli/api_utils.py
> +    print json.dumps(json.loads(text), indent=4, sort_keys=True)
So I had a look at the prettyprint library, and it seemed a bit long-winded to write a json formatter.

I'll have another look and see if there's something else I can do!

2017-02-02 11:59 UTC, stopal-r7 commented on lecli/api_utils.py
> +    print json.dumps(json.loads(text), indent=4, sort_keys=True)
we are using tabular in other api's for the moment: https://pypi.python.org/pypi/tabulate
but you can consider using this library as well: https://pypi.python.org/pypi/PTable/0.9.0

2017-02-02 13:53 UTC, stopal-r7 approved these changes
Adding a separator character line between log objects when listing logs can be a good one.

2017-02-02 17:33 UTC, stopal-r7 approved these changes

2017-02-02 17:33 UTC, stopal-r7 approved these changes
when Travis is happy.

2017-02-06 11:53 UTC, merged